### PR TITLE
bugfix for persistent connections

### PR DESCRIPTION
**Pull request by savar**
so for now the segfault should be gone but i have to test persistent connections when redis server goes down or is unreachable..

but one problem still exists and i'm not sure how to react to:

<pre>
$r->multi()->set("zzz", "DEF0");

// shutdown redis
sleep(10);

try {
   var_dump($r->get("zzz")->exec());
} catch(Exception $e) {}

// start redis
sleep(10);

// now the socket is in MULTI mode but it's not true..
var_dump($r->get("zzz")); // returnes FALSE
var_dump($r->set("zzz", "1234")); // returnes FALSE
</pre>

ok while i'm writing this i think i have to set the mode on an exception (read error or connection lost) to atomic, what do you think?

### CODE REVIEW

**Comment by savar** [comment]
ok now it should be ok.. testing with persistent connection is in the queue :S

**Comment by nicolasff** [comment]
All good for me then, the fix is quite short.

**Comment by nicolasff** [comment]
Pushed, congratulations :)

**Comment by savar** [comment]
it isn't as easy as i thought.. if redis servers goes down all went well but when rejecting the tcp packages then this happens:

<pre>
string(7) "+QUEUED"
bool(true)
------------------------------- second persistent --------------------
sleeping (shutdown)...

Fatal error: Call to a member function set() on a non-object in /home/s/plista/projekte/plista/packages/phpredis/test.php on line 87
</pre>


`+QUEUE` shouldn't be returned but something like 

<pre>
string(4) "9ABC"
bool(true)
</pre>


so i have to look into it again.

If you wanna test by yourself i would be happy so that a second pair of eyes are rolling over the stuff

**Comment by savar** [comment]
oh already pushed? nevermind i don't think it will be the normal case (rejecting tcp packages) but i'll fix it!

**Pull request merged**
