### PR TITLE
bugfix for broken connections

### PR DESCRIPTION
**Pull request by savar**
Hi Nicolas,

we have sometimes the problem, that the redis server is really down (we're tweaking at the moment) and i saw a problem when you try'ed this:

<pre>
$r->connect("X",1234); // connection established
// doing some stuff
// redis server get down (crash, shutdown whatever)
$r->get("x"); // "Connection lost" exception this time
$r->get("x"); // segfaults
</pre>

i think i fixed it but the problem exists in the multithreaded version (--enable-maintainer-zts) also and it wasn't really clear where the problem exists so i wasn't able to fix this. It's also easier to produce the error:

<pre>
$r->connect("X",1234); // connection established
$r->close();
$r->get("x"); // segfaults
</pre>

here a backtrace which is a little bit curious because the problem is in the exception initializing:

<pre>
Program received signal SIGSEGV, Segmentation fault.
0x0000000000717351 in zend_update_class_constants (class_type=0xd94cb0, tsrm_ls=0xf47050)
    at /home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_API.c:1003
1003            zend_class_entry **scope = EG(in_execution)?&EG(scope):&CG(active_class_entry);
(gdb) backtrace
#0  0x0000000000717351 in zend_update_class_constants (class_type=0xd94cb0, tsrm_ls=0xf47050)
    at /home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_API.c:1003
#1  0x00000000007179df in _object_and_properties_init (arg=0xf47568, class_type=0xd94cb0, properties=0x0, 
    __zend_filename=0xad01d8 "/home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_exceptions.c", __zend_lineno=706, tsrm_ls=0xf47050)
    at /home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_API.c:1075
#2  0x0000000000717b51 in _object_init_ex (arg=0xf47568, class_type=0xd94cb0, 
    __zend_filename=0xad01d8 "/home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_exceptions.c", __zend_lineno=706, tsrm_ls=0xf47050)
    at /home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_API.c:1096
#3  0x0000000000738f54 in zend_throw_exception (exception_ce=0xd94cb0, message=0x7fffefe48830 "Connection closed", code=0, 
    tsrm_ls=0xf47050) at /home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_exceptions.c:706
#4  0x00007fffefe4686c in redis_sock_write (redis_sock=0xf46e68, cmd=0xf47050 "*2\r\n$3\r\nGET\r\n$3\r\nxxx\r\n", sz=22, tsrm_ls=0xf47050)
    at /home/s/plista/projekte/plista/packages/phpredis/trunk/library.c:926
#5  0x00007fffefe1ecb5 in zim_Redis_get (ht=1, return_value=0xf46028, return_value_ptr=0x0, this_ptr=0xf460a8, return_value_used=1, 
    tsrm_ls=0xd3c090) at /home/s/plista/projekte/plista/packages/phpredis/trunk/redis.c:664
#6  0x0000000000750897 in zend_do_fcall_common_helper_SPEC (execute_data=0x7ffff7ec4098, tsrm_ls=0xd3c090)
    at /home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_vm_execute.h:316
#7  0x00000000007512d1 in ZEND_DO_FCALL_BY_NAME_SPEC_HANDLER (execute_data=0x7ffff7ec4098, tsrm_ls=0xd3c090)
    at /home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_vm_execute.h:421
#8  0x000000000074f879 in execute (op_array=0xf46d20, tsrm_ls=0xd3c090)
    at /home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend_vm_execute.h:107
#9  0x00000000007128b9 in zend_execute_scripts (type=8, tsrm_ls=0xd3c090, retval=0x0, file_count=3)
    at /home/s/plista/projekte/plista/php/php5-5.3.3/Zend/zend.c:1194
#10 0x0000000000672330 in php_execute_script (primary_file=0x7fffffffe000, tsrm_ls=0xd3c090)
    at /home/s/plista/projekte/plista/php/php5-5.3.3/main/main.c:2260
#11 0x000000000081ef46 in main (argc=2, argv=0x7fffffffe258) at /home/s/plista/projekte/plista/php/php5-5.3.3/sapi/cli/php_cli.c:1192
</pre>

and that's what i did:

<pre>
$r = new Redis();
var_dump($r->get("xxx"));
$r->connect("localhost", 6379, 12);
$r->close();
var_dump($r->get("xxx"));
</pre>

cheers

### CODE REVIEW

**Comment by nicolasff** [comment]
Simon,

Thank you for your involvement in phpredis :-)
It's a bit late for me here in Paris but I'll have a look tomorrow morning and I'll add unit tests as well to make sure this doesn't break anything.

Cheers,

Nicolas

**Comment by savar** [comment]
Thx a lot. And yes here in Berlin it's not sooner or later i think ;)

**Comment by nicolasff** [comment]
This is merged, thanks. I'll investigate the problem with maintainer-zts.

**Comment by nicolasff** [comment]
I can reproduce the crash, but not in the same place. 

<pre>
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread -1212246336 (LWP 12035)]
0x08316bc4 in _zend_list_delete (id=4, tsrm_ls=0xb7bb6fc4) at /usr/src/php-5.3.3/Zend/zend_list.c:55
55      if (zend_hash_index_find(&EG(regular_list), id, (void **) &le)==SUCCESS) {
(gdb) bt
#0  0x08316bc4 in _zend_list_delete (id=4, tsrm_ls=0xb7bb6fc4) at /usr/src/php-5.3.3/Zend/zend_list.c:55
#1  0x082c9766 in _php_stream_free (stream=0xb7bb61f8, close_options=3, tsrm_ls=0xb7bb6fc4) at /usr/src/php-5.3.3/main/streams/streams.c:335
#2  0xb7a52937 in redis_check_eof (redis_sock=0xb7bb6134, tsrm_ls=0xb7bb6fc4) at /home/owlient/phpredis/library.c:24
#3  0xb7a54ab3 in redis_sock_write (redis_sock=0xb7bb6134, cmd=0xb7bb6368 "*2\r\n$3\r\nGET\r\n$1\r\nx\r\n", sz=20, tsrm_ls=0xb7bb6fc4) at /home/owlient/phpredis/library.c:931
#4  0xb7a393b6 in zim_Redis_get (ht=1, return_value=0xb7bb6318, return_value_ptr=0x0, this_ptr=0xb7bb5364, return_value_used=0, tsrm_ls=0x8648050) at /home/owlient/phpredis/redis.c:664
#5  0x0832d04e in zend_do_fcall_common_helper_SPEC (execute_data=0xb79f1028, tsrm_ls=0x8648050) at /usr/src/php-5.3.3/Zend/zend_vm_execute.h:316
#6  0x0832c24e in execute (op_array=0xb7bb57f4, tsrm_ls=0x8648050) at /usr/src/php-5.3.3/Zend/zend_vm_execute.h:107
#7  0x0830ad5c in zend_execute_scripts (type=8, tsrm_ls=0x8648050, retval=0x0, file_count=3) at /usr/src/php-5.3.3/Zend/zend.c:1194
#8  0x082b660f in php_execute_script (primary_file=0xbff86900, tsrm_ls=0x8648050) at /usr/src/php-5.3.3/main/main.c:2260
#9  0x08388893 in main (argc=2, argv=0xbff869e4) at /usr/src/php-5.3.3/sapi/cli/php_cli.c:1192
</pre>


This is still linked to the stream deletion. I'm really not sure what to do; I tried skipping the call to php_stream_close() when maintainer ZTS is enabled, but it crashed upon reconnection.

This is the script I'm using:

<pre>
&lt;?php

$r = new Redis;
$r->connect('127.0.0.1');
// doing some stuff
echo "Kill Redis now.\n";
sleep(5); 
try {
    echo "First get...\n";
    $r->get("x"); // "Connection lost" exception this time
}catch(Exception $e) {
    echo "Exception!\n";
}
echo "GET again...\n";
$r->get("x"); // segfaults
?>
</pre>

**Comment by savar** [comment]
oh yes i remember that i also runned into

<pre>
0x08316bc4 in _zend_list_delete (id=4, tsrm_ls=0xb7bb6fc4) at /usr/src/php-5.3.3/Zend/zend_list.c:55
55      if (zend_hash_index_find(&EG(regular_list), id, (void **) &le)==SUCCESS) {
</pre>


and i give up yesterday because it seems to something weird.. i'm not really comfortable with the threading stuff and also the book makes me more crazy then explains it really.. i'm not sure if i can define a static variable like for a HashTable and access it "normally" when ZTS is enabled.. :( maybe this is a problem in this case..

**Pull request merged**
