### PR TITLE
fix bug for rejected packages and persistent connections

### PR DESCRIPTION
**Pull request by savar**
ok so i have also to close the connection to be sure to avoid this special case. but my (manual) test are working now. could you check this also? THX

### CODE REVIEW

**Comment by nicolasff** [comment]
This could be refactored into a single function that would check the `persistent` flag, what do you think?

**Comment by savar** [comment]
yes i also thought about it.. if you want to i'll do it

**Comment by nicolasff** [comment]
Perfect.

**Comment by savar** [comment]
ok there you're ... i'm not sure if a define wouldn't be better or at least an inline function?

**Comment by nicolasff** [comment]
It shouldn't matter very much, GCC will inline it if needed. That's not really a critical piece of code.

**Pull request merged**
